# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 7 # it will paginate after this number
language: 'en-uk'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Donal Rafferty
description: Imagination will often carry us to worlds that never were. But without it we go nowhere.
cover: assets/images/blog-cover.jpg
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
# production_url: https://myJekyll.github.io/jasper2/
# source_url: https://github.com/myJekyll/jasper2/

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: donalnotdonald # replace by your username

# Disqus
disqus: True
disqus_shortname: donalrafferty # replace with your disqus username

# Google Analytics
# google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
# permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
url: "https://blog.donalrafferty.com"
plugins: [jekyll-paginate, jekyll-feed, 'jekyll/scholar', jekyll-sitemap]
exclude: [vendor]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
# safe: False
# lsi: False
# username: myJekyll
# repo: jasper2
# branch: master
# relative_source: ./
# destination: ./_site
# production_url:  https://blog.donalrafferty.com
# source_url:  https://github.com/myJekyll/jasper2/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - firebase.json
  - .firebaserc
  - gulpfile.js
  - package.json
  - script.py
  - node_modules

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: _bibliography
  bibliography: bibliography.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
